### ISSUE TITLE
package for highlighting uncommitted changes

### ISSUE THREAD

**Issue by edgarkhanzadyan** [Fuco1/.emacs.d#37]
Hi there! So the question is:
Do you use any package for highlighting uncommitted changes in the file?
I use diff-hl but it's kinda laggy :(
<img width="484" alt="screen shot 2018-03-05 at 12 07 17 am" src="https://user-images.githubusercontent.com/22010816/36949994-37ca299e-2009-11e8-93b5-c57b66b3fbd3.png">

**Comment by Fuco1** [comment]
I personally don't use it but I've heard good things about https://github.com/syohex/emacs-git-gutter

I usually jump into `vc-diff` or magit, but it's not part of my regular workflow.

**Comment by edgarkhanzadyan** [comment]
Okay, will definitely try those! Thanks a lot! :D
