### ISSUE TITLE
`org-get-local-archive-location` and `org-extract-archive-file` are no more.

### ISSUE THREAD

**Issue by michaelcadilhac** [Fuco1/.emacs.d#62]
For some reason, the above two functions are not in org anymore. 
 The following should be adjusted: 
https://github.com/Fuco1/.emacs.d/blob/b64c9c30ec851b21b8353186d11007039b84a028/files/org-defs.el#L1817

**Comment by Fuco1** [comment]
Some people had update versions in the gist I posted: https://gist.github.com/Fuco1/e86fb5e0a5bb71ceafccedb5ca22fcfb

**Comment by michaelcadilhac** [comment]
Didn't see that, apologies.  I got to your repo through your [blog post](https://fuco1.github.io/2017-04-20-Archive-subtrees-under-the-same-hierarchy-as-original-in-the-archive-files.html), which didn't refer to a gist, AFAICS.  Thanks for your work; feel free to close if you don't want to track that issue here.

**Comment by Fuco1** [comment]
No worries!  I put it in the gist for some reason (I don't remember) and others found it and started discussing there.  I think I'll keep it open here because when I migrate it's going to stop working for me :D

**Comment by novoid** [comment]
I had the very same issue and the code from [this comment](https://gist.github.com/Fuco1/e86fb5e0a5bb71ceafccedb5ca22fcfb#gistcomment-3006243) works at my side with emacs-version 26.3 and org-version 9.3.
