### ISSUE TITLE
Logic behind your keybindings?

### ISSUE THREAD

**Issue by extralight** [Fuco1/.emacs.d#63]
Could you explain why you have chosen the keybindings in
https://github.com/Fuco1/.emacs.d/blob/master/files/smartparens.el

Ex.: Keys like C-M-a are the opposite of what is expected.

Whereas the article you have linked to in your homepage
https://ebzzry.io/en/emacs-pairs/
has more relatable bindings.

Why?

**Comment by Fuco1** [comment]
To be honest I don't remember.  I doubt there was some deep logic behind it, I probably just picked the empty available bindings.
